name: Fetch Data

on:
  schedule:
    - cron: "0 8 * * 2"
  workflow_dispatch:

permissions:
  contents: read
env:
  season: 2024
jobs:
  fetch:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/bspaulding/nfl-data-scraper:main
    steps:
    - name: Fetch
      run: nfl-data-scraper -c fetch -s ${{ env.season }} -o player-data.json
    - name: Upload data
      uses: actions/upload-artifact@v4
      with:
        name: player-data
        path: player-data.json
    - name: Export
      run: nfl-data-scraper -c export -s ${{ env.season }} -i player-data.json -o player-data.sdio.json
    - name: Upload export
      uses: actions/upload-artifact@v4
      with:
        name: player-data-sdio
        path: player-data.sdio.json
  upload:
    needs: fetch
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/amazonlinux/amazonlinux:latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - run: yum update && yum install -y awscli
    - name: Download export
      uses: actions/download-artifact@v4
      with:
        name: player-data-sdio
        path: player-data-sdio
    - name: Upload to S3
      run: aws s3 cp ./player-data-sdio/player-data.sdio.json s3://nfl-stats.motingo.com/api/players/${{ env.season }}.json
