name: Fetch Data

on:
  schedule:
    - cron: "0 8 * * 2"
  workflow_dispatch:

permissions:
  contents: read
env:
  season: 2024
jobs:
  fetch:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/bspaulding/nfl-data-scraper:main
    steps:
    - name: Fetch
      run: nfl-data-scraper -c fetch -s ${{ env.season }} -o player-data.json
    - name: Upload data
      uses: actions/upload-artifact@v4
      with:
        name: player-data
        path: player-data.json
    - name: Export
      run: nfl-data-scraper -c export -s ${{ env.season }} -i player-data.json -o player-data.sdio.json
    - name: Upload export
      uses: actions/upload-artifact@v4
      with:
        name: player-data-sdio
        path: player-data.sdio.json
  calculate-vorp:
    needs: fetch
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/bspaulding/nfl-vorp:main
    steps:
    - name: Download export
      uses: actions/download-artifact@v4
      with:
        name: player-data-sdio
        path: player-data-sdio
    - name: Calculate VORP
      run: deno run --allow-read --allow-write /vorp/vorp-cli.ts player-data-sdio/player-data.sdio.json
    - name: Upload vorp
      uses: actions/upload-artifact@v4
      with:
        name: vorp
        path: out.csv
  upload-player-data:
    needs: fetch
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/amazonlinux/amazonlinux:latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
    - run: yum update && yum install -y awscli
    - name: Download export
      uses: actions/download-artifact@v4
      with:
        name: player-data-sdio
        path: player-data-sdio
    - name: Upload player data to S3
      run: aws s3 cp ./player-data-sdio/player-data.sdio.json s3://nfl-stats.motingo.com/api/players/${{ env.season }}.json
  upload-vorp:
    needs: calculate-vorp
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/amazonlinux/amazonlinux:latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
    - run: yum update && yum install -y awscli
    - name: Download vorp
      uses: actions/download-artifact@v4
      with:
        name: vorp
        path: vorp
    - name: Upload vorp to S3
      run: aws s3 cp ./vorp/out.csv s3://nfl-stats.motingo.com/api/vorp/${{ env.season }}.csv
