name: Fetch Data

on:
  schedule:
    - cron: "0 8 * * 2"
  workflow_dispatch:
    
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/bspaulding/nfl-data-scraper:main
    steps:
    - name: Fetch
      run: nfl-data-scraper -c fetch -s 2024 -o player-data.json
    - name: Upload data
      uses: actions/upload-artifact@v4
      with:
        name: player-data
        path: player-data.json
    - name: Export
      run: nfl-data-scraper -c export -s 2024 -i player-data.json -o player-data.sdio.json
    - name: Upload export
      uses: actions/upload-artifact@v4
      with:
        name: player-data-sdio
        path: player-data.sdio.json
